apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
  namespace: dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: beat

  template:
    metadata:
      labels:
        app: beat

    spec:

      containers:

        - name: beat
          image: hanihammadeh/status-monitor:initial

          command:
            - celery

          args:
            - -A
            - app.celery_app
            - beat
            - --loglevel=info


          env:
            - name: DATABASE_URL
              value: postgresql://statususer:statuspass@db:5432/statusdb

            - name: REDIS_URL
              value: redis://redis:6379/0